trigger:
- master

pool:
  vmImage: $(VmImage)

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "[" + $env:VCTargetsPath + "]"
      ls -Name -Recurse 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\'
    pwsh: true

- task: MSBuild@1
  inputs:
    platform: x86
    configuration: Debug
    solution: $(Build.SourcesDirectory)\Source\Cpp\Project64\3rdParty\duktape\duktape.vcxproj
    msbuildArguments: /p:PlatformToolset=v141
